// https://github.com/uwu/shelter/blob/main/packages/shelter/src/types.ts
// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bf9d37548ce8121a062f48434b84637ac3363ecf/types/react-reconciler/index.d.ts

import type {
	$$context,
	$$forwardRef,
	$$fragment,
	$$lazy,
	$$memo,
	$$provider,
	WorkTag,
} from "./autogenerated/react@19.2.4.ts";
export * from "./autogenerated/react@19.2.4.ts";

export interface ReactMemoType {
	$$typeof: typeof $$memo;
	type: ComponentType;
	compare: Function | null;
}

export interface ReactForwardRefType {
	$$typeof: typeof $$forwardRef;
	render: Function;
}

export interface ReactFragment {
	$$typeof: typeof $$fragment;
}

export interface ReactLazy {
	$$typeof: typeof $$lazy;
	_payload: unknown;
	_init: Function;
}

export interface ReactContext<T> {
	$$typeof: typeof $$context;
	displayName?: string;
	_currentValue: T;
	_currentValue2: T;
	_threadCount: number;
	Consumer: ReactContext<T>;
	Provider: ReactProviderType<T>;
}

export interface ReactProviderType<T> {
	$$typeof: typeof $$provider;
	_context: ReactContext<T>;
}

export type ComponentType = string | Function;

export type SpecialFiberType =
	| ReactMemoType
	| ReactForwardRefType
	| ReactContext<unknown>
	| ReactProviderType<unknown>
	| ReactLazy
	| ReactFragment;

export type FiberElementType = ComponentType | SpecialFiberType;

export interface HookNode<S = unknown> {
	memoizedState: S;
	queue: unknown;
	next: HookNode | null;
}

export interface ContextDependency<T> {
	context: ReactContext<T>;
	next: ContextDependency<unknown> | null;
}

export interface Dependencies {
	lanes: number;
	firstContext: ContextDependency<unknown> | null;
}

export type FiberRef =
	| null
	| (((handle: unknown) => void) & { _stringRef?: string | null })
	| { current: unknown };

export interface Fiber {
	tag: WorkTag;
	key: string | null;
	type: FiberElementType;
	elementType: FiberElementType;
	stateNode: unknown;

	return: Fiber | null;
	child: Fiber | null;
	sibling: Fiber | null;
	index: number;

	ref: FiberRef;
	pendingProps: Record<string, unknown>;
	memoizedProps: Record<string, unknown>;

	memoizedState: HookNode | null | unknown;
	updateQueue: unknown;
	dependencies: Dependencies | null;

	flags: number;
	subtreeFlags: number;
	deletions: Fiber[] | null;
	lanes: number;
	childLanes: number;
	mode: number;
	alternate: Fiber | null;

	actualDuration?: number;
	actualStartTime?: number;
	selfBaseDuration?: number;
	treeBaseDuration?: number;
}
