#!/usr/bin/env -S deno run --allow-net --allow-write

type WorkTags = Record<string, number>;

interface FlagExpression {
	readonly name: string;
	readonly expression: string;
}

interface ReactSources {
	workTags: string;
	flags: string;
}

interface ParsedReactData {
	workTags: WorkTags;
	flags: readonly FlagExpression[];
}

const REPO_BASE_URL = "https://raw.githubusercontent.com/facebook/react";

const SOURCE_PATHS = {
	workTags: "packages/react-reconciler/src/ReactWorkTags.js",
	flags: "packages/react-reconciler/src/ReactFiberFlags.js",
} as const;

function getVersion(): string {
	const version = Deno.args[0];
	if (!version) {
		console.error("error: please provide a React version (e.g., 18.2.0)");
		Deno.exit(1);
	}
	return version;
}

async function fetchFile(tag: string, path: string): Promise<string> {
	const url = `${REPO_BASE_URL}/${tag}/${path}`;
	console.log(`· ${url}`);
	const res = await fetch(url);
	if (!res.ok) {
		throw new Error(`failed to fetch ${url}: ${res.statusText}`);
	}
	return res.text();
}

async function fetchSources(version: string): Promise<ReactSources> {
	const tag = `refs/tags/v${version}`;
	const [workTags, flags] = await Promise.all([
		fetchFile(tag, SOURCE_PATHS.workTags),
		fetchFile(tag, SOURCE_PATHS.flags),
	]);
	return { workTags, flags };
}

async function writeOutput(version: string, content: string): Promise<void> {
	const path = `packages/types/src/autogenerated/react@${version}.ts`;

	await Deno.writeTextFile(path, content);
	console.log(`+ ${path}`);
}

const stripComments = (code: string): string =>
	code.replace(/\/\*[\s\S]*?\*\//g, "")
		.replace(/\/\/.*/g, "");

const simplifyTernaries = (expr: string): string =>
	expr.replace(/\(?\s*\w+\s*\?[^:]+:[^)]+\)?/g, "0") // (cond ? a : b) -> 0
		.replace(/\s+/g, " ")
		.trim();

function parseWorkTags(source: string): WorkTags {
	const pattern = /export const (\w+)\s*=\s*(\d+)/g;
	return Object.fromEntries(
		[...source.matchAll(pattern)].map((
			[, name, value],
		) => [name, parseInt(value, 10)]),
	);
}

function parseFlags(source: string): readonly FlagExpression[] {
	const pattern = /export const (\w+)\s*=\s*([^;]+)/g;

	return [...stripComments(source).matchAll(pattern)].map(([, name, expr]) => ({
		name,
		expression: simplifyTernaries(expr),
	}));
}

function getFlagComment(name: string): string | null {
	switch (name) {
		case "HostEffectMask":
			return "// union of all commit flags (flags with the lifetime of a particular commit)";
		case "MutationMask":
			return "// commit-phase traversal masks that React uses internally to decide\n// whether to enter each sub-phase";
		default:
			return null;
	}
}

function formatWorkTags(tags: WorkTags): string {
	return Object.entries(tags)
		.map(([k, v]) => `export const ${k} = ${v};`)
		.join("\n");
}

function formatEffectFlags(flags: readonly FlagExpression[]): string {
	const publicFlags = flags.filter(({ name }) => !name.startsWith("_"));

	return publicFlags.map(({ name, expression }) => {
		const comment = getFlagComment(name);
		const line = `export const ${name} = ${expression};`;
		return comment ? `\n${comment}\n${line}\n` : line;
	}).join("\n");
}

function generateOutput(version: string, data: ParsedReactData): string {
	return `// source refs:
// - packages/react-reconciler/src/ReactWorkTags.js
// - packages/react-reconciler/src/ReactFiberFlags.js
// - packages/shared/ReactSymbols.js
// auto-generated for react v${version}

export const $$memo = Symbol.for("react.memo");
export const $$forwardRef = Symbol.for("react.forward_ref");
export const $$fragment = Symbol.for("react.fragment");
export const $$provider = Symbol.for("react.provider");
export const $$context = Symbol.for("react.context");
export const $$lazy = Symbol.for("react.lazy");

${formatWorkTags(data.workTags)}

// fiber.tag is one of these integers
export const WorkTags = Object.freeze(
	{
		${Object.keys(data.workTags).join(", ")}
	} as const,
);

export type WorkTag = typeof WorkTags[keyof typeof WorkTags];

export const TagName: Readonly<Record<number, string>> = Object.fromEntries(
	Object.entries(WorkTags).map(([k, v]) => [v, k]),
);

${formatEffectFlags(data.flags)}

// exact bit values from ReactFiberFlags.js @ v${version}.
export const EffectFlags = Object.freeze(
	{
		${Object.values(data.flags).map((flag) => flag.name).join(", ")}
	} as const,
);

export const BeforeMutationMask: number = Snapshot | 0;

export const SUBTREE_MASK: number = BeforeMutationMask | MutationMask | LayoutMask | PassiveMask;
`;
}

async function main() {
	try {
		const version = getVersion();
		const sources = await fetchSources(version);

		const data: ParsedReactData = {
			workTags: parseWorkTags(sources.workTags),
			flags: parseFlags(sources.flags),
		};

		const output = generateOutput(version, data);
		await writeOutput(version, output);
	} catch (err) {
		console.error(err);
		Deno.exit(1);
	}
}

main();
